dist: precise
language: java
jdk:
  - oraclejdk8

cache:
  directories:
  - $HOME/.m2

install:
  - pushd contrib/read-properties
  - mvn -q install
  - popd
  - pushd contrib/assert-properties
  - mvn -q install
  - popd

script:
  - travis_wait mvn -q -Pdev,dist,microservices install -DskipTests
  - mvn -Dsurefire.forkCount=4 -Pdev verify
